export default {
  GAME_WIDTH: 160,
  GAME_HEIGHT: 256,

  BLOCK_SIDE_LENGTH: 16,

  BOARD_WIDTH: 10,
  BOARD_HEIGHT: 16,

  NUMBER_OF_COLORS: 7,
  COLOR_BLUE: 0,
  COLOR_CYAN: 1,
  COLOR_GREEN: 2,
  COLOR_ORANGE: 3,
  COLOR_PURPLE: 4,
  COLOR_RED: 5,
  COLOR_YELLOW: 6,

  NUMBER_OF_BLOCKS_IN_SHAPE: 4,
  NUMBER_OF_SHAPE_TYPES: 7,
  NUMBER_OF_SHAPE_ORIENTATIONS: 4,
};
